FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

# Databricks CLI 설치
RUN curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

# 기본 작업 디렉토리 설정
WORKDIR /workspace
